version: "3.8"
services:
  postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: TEMPORARY_PASSWORD
      POSTGRES_DB: monolithicWebapp
    ports:
      - "5432:5432"


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app1
      - app2
      - app3

  app1:
    container_name: proyecto_docker1
    image: umibana/monolithicwebapp:latest
    build: .
    ports:
      - "8091:8090"
    platform: linux/amd64
    environment:
      - SPRING_APPLICATION_NAME=monolithicWebapp
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/monolithicWebapp
      - SERVER_PORT = 8090
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=TEMPORARY_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db

  app2:
    container_name: proyecto_docker2
    image: umibana/monolithicwebapp:latest
    build: .
    platform: linux/amd64
    ports:
      - "8092:8090"
    environment:
      - SPRING_APPLICATION_NAME=monolithicWebapp
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/monolithicWebapp
      - SERVER_PORT = 8090
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=TEMPORARY_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db

  app3:
    container_name: proyecto_docker3
    image: umibana/monolithicwebapp:latest
    build: .
    platform: linux/amd64
    ports:
      - "8093:8090"
    environment:
      - SPRING_APPLICATION_NAME=monolithicWebapp
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/monolithicWebapp
      - SERVER_PORT = 8090
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=TEMPORARY_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres-db